apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: 696c0kqj7-go 
  janus-idp.io/tekton: 696c0kqj7-go
  backstage.io/kubernetes-id: 696c0kqj7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 696c0kqj7-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  