apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: 696c0kqj7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 696c0kqj7-go 
  name: 696c0kqj7-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: 696c0kqj7-go 
